var $jscomp={scope:{},owns:function(b,a){return Object.prototype.hasOwnProperty.call(b,a)}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var f=b[d];f in c||(c[f]={});c=c[f]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Object.assign",function(b){return b?b:function(a,b){for(var c=1;c<arguments.length;c++){var f=arguments[c];if(f)for(var g in f)$jscomp.owns(f,g)&&(a[g]=f[g])}return a}},"es6-impl","es3");
(function(b,a){if("function"===typeof define&&define.amd)define(["exports"],a);else if("undefined"!==typeof exports)a(exports);else{var c={};a(c);b.actual=c}})(this,function(b){Object.defineProperty(b,"__esModule",{value:!0});var a=b,a=b;a.NAMESPACE=a.namespace=null;a.NAMESPACES=a.namespaces={svg:"http://www.w3.org/2000/svg",html:"http://www.w3.org/1999/xhtml",xlink:"http://www.w3.org/1999/xlink"};a._=function(b,d){for(var c=a.NAMESPACE?document.createElementNS(null,b):document.createElement(b),g=
function(b,c){if(void 0!=c)if("string"==typeof c)b.appendChild(document.createTextNode(c));else if("object"==typeof c&&"undefined"!=typeof c.jquery)for(var e=0;e<c.length;e++)g(b,c[e]);else if("object"==typeof c&&"undefined"!=typeof c.nodeType)b.appendChild(c);else if("object"==typeof c&&c instanceof Array)for(e=0;e<c.length;e++)g(b,c[e]);else{var d=!1;for(e in c){var d=null,f=e.lastIndexOf(":"),h=c[e];0<=f&&(d=e.substr(0,f),d=a.NAMESPACES[d]||d,e=e.substr(f+1,e.length));if("_"==e||"_class"==e||"klass"==
e)e="class";d?b.setAttributeNS(d,e,h):b.setAttribute(e,h);d=!0}d||b.appendChild(document.createTextNode(""+c))}},h=0;h<d.length;h++)g(c,d[h]);return c};a.address=function(){return a._("address",arguments)};a.applet=function(){return a._("applet",arguments)};a.area=function(){return a._("area",arguments)};a.a=function(){return a._("a",arguments)};a.base=function(){return a._("base",arguments)};a.basefont=function(){return a._("basefont",arguments)};a.big=function(){return a._("big",arguments)};a.blockquote=
function(){return a._("blockquote",arguments)};a.body=function(){return a._("body",arguments)};a.br=function(){return a._("br",arguments)};a.b=function(){return a._("b",arguments)};a.caption=function(){return a._("caption",arguments)};a.center=function(){return a._("center",arguments)};a.cite=function(){return a._("cite",arguments)};a.code=function(){return a._("code",arguments)};a.dd=function(){return a._("dd",arguments)};a.dfn=function(){return a._("dfn",arguments)};a.dir=function(){return a._("dir",
arguments)};a.div=function(){return a._("div",arguments)};a.dl=function(){return a._("dl",arguments)};a.dt=function(){return a._("dt",arguments)};a.em=function(){return a._("em",arguments)};a.font=function(){return a._("font",arguments)};a.form=function(){return a._("form",arguments)};a.h1=function(){return a._("h1",arguments)};a.h2=function(){return a._("h2",arguments)};a.h3=function(){return a._("h3",arguments)};a.h4=function(){return a._("h4",arguments)};a.h5=function(){return a._("h5",arguments)};
a.h6=function(){return a._("h6",arguments)};a.head=function(){return a._("head",arguments)};a.hr=function(){return a._("hr",arguments)};a.html=function(){return a._("html",arguments)};a.img=function(){return a._("img",arguments)};a.input=function(){return a._("input",arguments)};a.isindex=function(){return a._("isindex",arguments)};a.i=function(){return a._("i",arguments)};a.kbd=function(){return a._("kbd",arguments)};a.link=function(){return a._("link",arguments)};a.li=function(){return a._("li",
arguments)};a.map=function(){return a._("map",arguments)};a.menu=function(){return a._("menu",arguments)};a.meta=function(){return a._("meta",arguments)};a.ol=function(){return a._("ol",arguments)};a.option=function(){return a._("option",arguments)};a.param=function(){return a._("param",arguments)};a.pre=function(){return a._("pre",arguments)};a.p=function(){return a._("p",arguments)};a.samp=function(){return a._("samp",arguments)};a.script=function(){return a._("script",arguments)};a.select=function(){return a._("select",
arguments)};a.small=function(){return a._("small",arguments)};a.strike=function(){return a._("strike",arguments)};a.strong=function(){return a._("strong",arguments)};a.style=function(){return a._("style",arguments)};a.sub=function(){return a._("sub",arguments)};a.sup=function(){return a._("sup",arguments)};a.table=function(){return a._("table",arguments)};a.td=function(){return a._("td",arguments)};a.textarea=function(){return a._("textarea",arguments)};a.th=function(){return a._("th",arguments)};
a.title=function(){return a._("title",arguments)};a.tr=function(){return a._("tr",arguments)};a.tt=function(){return a._("tt",arguments)};a.ul=function(){return a._("ul",arguments)};a.u=function(){return a._("u",arguments)};a["var"]=a._var=function(){return a._("var",arguments)};a.a=function(){return a._("a",arguments)};a.abbr=function(){return a._("abbr",arguments)};a.acronym=function(){return a._("acronym",arguments)};a.address=function(){return a._("address",arguments)};a.applet=function(){return a._("applet",
arguments)};a.area=function(){return a._("area",arguments)};a.article=function(){return a._("article",arguments)};a.aside=function(){return a._("aside",arguments)};a.audio=function(){return a._("audio",arguments)};a.b=function(){return a._("b",arguments)};a.base=function(){return a._("base",arguments)};a.basefont=function(){return a._("basefont",arguments)};a.bdo=function(){return a._("bdo",arguments)};a.big=function(){return a._("big",arguments)};a.blockquote=function(){return a._("blockquote",arguments)};
a.body=function(){return a._("body",arguments)};a.br=function(){return a._("br",arguments)};a.button=function(){return a._("button",arguments)};a.canvas=function(){return a._("canvas",arguments)};a.caption=function(){return a._("caption",arguments)};a.center=function(){return a._("center",arguments)};a.cite=function(){return a._("cite",arguments)};a.code=function(){return a._("code",arguments)};a.col=function(){return a._("col",arguments)};a.colgroup=function(){return a._("colgroup",arguments)};a.command=
function(){return a._("command",arguments)};a.datalist=function(){return a._("datalist",arguments)};a.dd=function(){return a._("dd",arguments)};a.del=function(){return a._("del",arguments)};a.details=function(){return a._("details",arguments)};a.dfn=function(){return a._("dfn",arguments)};a.dir=function(){return a._("dir",arguments)};a.div=function(){return a._("div",arguments)};a.dl=function(){return a._("dl",arguments)};a.dt=function(){return a._("dt",arguments)};a.em=function(){return a._("em",
arguments)};a.embed=function(){return a._("embed",arguments)};a.fieldset=function(){return a._("fieldset",arguments)};a.figcaption=function(){return a._("figcaption",arguments)};a.figure=function(){return a._("figure",arguments)};a.font=function(){return a._("font",arguments)};a.footer=function(){return a._("footer",arguments)};a.form=function(){return a._("form",arguments)};a.frame=function(){return a._("frame",arguments)};a.frameset=function(){return a._("frameset",arguments)};a.h1=function(){return a._("h1",
arguments)};a.head=function(){return a._("head",arguments)};a.header=function(){return a._("header",arguments)};a.hgroup=function(){return a._("hgroup",arguments)};a.hr=function(){return a._("hr",arguments)};a.html=function(){return a._("html",arguments)};a.i=function(){return a._("i",arguments)};a.iframe=function(){return a._("iframe",arguments)};a.img=function(){return a._("img",arguments)};a.input=function(){return a._("input",arguments)};a.ins=function(){return a._("ins",arguments)};a.keygen=
function(){return a._("keygen",arguments)};a.kbd=function(){return a._("kbd",arguments)};a.label=function(){return a._("label",arguments)};a.legend=function(){return a._("legend",arguments)};a.li=function(){return a._("li",arguments)};a.link=function(){return a._("link",arguments)};a.map=function(){return a._("map",arguments)};a.mark=function(){return a._("mark",arguments)};a.menu=function(){return a._("menu",arguments)};a.meta=function(){return a._("meta",arguments)};a.meter=function(){return a._("meter",
arguments)};a.nav=function(){return a._("nav",arguments)};a.noframes=function(){return a._("noframes",arguments)};a.noscript=function(){return a._("noscript",arguments)};a.object=function(){return a._("object",arguments)};a.ol=function(){return a._("ol",arguments)};a.optgroup=function(){return a._("optgroup",arguments)};a.option=function(){return a._("option",arguments)};a.output=function(){return a._("output",arguments)};a.p=function(){return a._("p",arguments)};a.param=function(){return a._("param",
arguments)};a.pre=function(){return a._("pre",arguments)};a.progress=function(){return a._("progress",arguments)};a.q=function(){return a._("q",arguments)};a.rp=function(){return a._("rp",arguments)};a.rt=function(){return a._("rt",arguments)};a.ruby=function(){return a._("ruby",arguments)};a.s=function(){return a._("s",arguments)};a.samp=function(){return a._("samp",arguments)};a.script=function(){return a._("script",arguments)};a.section=function(){return a._("section",arguments)};a.select=function(){return a._("select",
arguments)};a.small=function(){return a._("small",arguments)};a.source=function(){return a._("source",arguments)};a.span=function(){return a._("span",arguments)};a.strike=function(){return a._("strike",arguments)};a.strong=function(){return a._("strong",arguments)};a.style=function(){return a._("style",arguments)};a.sub=function(){return a._("sub",arguments)};a.summary=function(){return a._("summary",arguments)};a.sup=function(){return a._("sup",arguments)};a.table=function(){return a._("table",arguments)};
a.tbody=function(){return a._("tbody",arguments)};a.td=function(){return a._("td",arguments)};a.textarea=function(){return a._("textarea",arguments)};a.tfoot=function(){return a._("tfoot",arguments)};a.th=function(){return a._("th",arguments)};a.thead=function(){return a._("thead",arguments)};a.time=function(){return a._("time",arguments)};a.title=function(){return a._("title",arguments)};a.tr=function(){return a._("tr",arguments)};a.tt=function(){return a._("tt",arguments)};a.u=function(){return a._("u",
arguments)};a.ul=function(){return a._("ul",arguments)};a["var"]=a._var=function(){return a._("var",arguments)};a.video=function(){return a._("video",arguments)};a.wbr=function(){return a._("wbr",arguments)};a.xmp=function(){return a._("xmp",arguments)};Object.assign(b,a);"undefined"!==typeof extend&&extend.module("html",a);"undefined"!==typeof window&&(window.html=a);return b});
