var $jscomp={scope:{},findInternal:function(b,a,c){b instanceof String&&(b=String(b));for(var d=b.length,e=0;e<d;e++){var f=b[e];if(a.call(c,f,e,b))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in c||(c[e]={});c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6-impl","es3");var smalldoc="undefined"!=typeof extend?extend.module("smalldoc"):"undefined"!=typeof smalldoc?smalldoc:{};
(function(b){b.LICENSE="http://ffctn.com/doc/licenses/bsd";b.DATA=null;b.OPTIONS={containers:3,data:"api.json",sort:{section:!1,document:!1,module:!1}};b.STATE={active:[],symbols:{}};b.GROUPS="document;section;parent;module;class;class constructor;class attribute;class method;attribute;method;function;value".split(";");b.GROUPS_CHILDREN="class attribute;attribute;value;class method;class constructor;method;function".split(";");b.loadCSS=function(b){void 0===b&&(b=null);return b?(b=html.link({href:b+
fonts,rel:"stylesheet"}),document.head.appendChild(b),b):null};b.load=function(a){void 0===a&&(a=b.OPTIONS.data);fetch(a).then(function(a){return a.json().then(b.setup)})};b.setup=function(a){void 0===a&&(a=b.DATA);if(b.STATE.initialized)return!1;b.DATA=a;var c=b.ensureNode("smalldoc",document.body);b.ensureNode("containers",c);b.ensureNode("description",c);b.ensureNode("hidden",c);b.ensureNode("about",c,function(b){b.innerHTML="<a href='https://github.com/sebastien/smalldoc'>smalldoc</a>"});b.render(a);
window.addEventListener("hashchange",b.onHashChange);b.onHashChange();b.STATE.initialized=!0};b.ensureNode=function(b,c,d){void 0===d&&(d=void 0);var a=document.getElementById(b);a||(a=html.div({id:b}),d&&d(a),c.appendChild(a));return a};b.render=function(a,c){void 0===c&&(c=null);b.renderContainer(a,c||a.title||"Smalldoc","document")};b.show=function(a,c){void 0===c&&(c=b.OPTIONS.containers);var d=b.STATE.symbols[a];if(d||!b.STATE.previous){b.STATE.previous=d;b._clearContainers();b._showContainer("__root__");
(a||"").split(".").reduce(function(a,c){return b._showContainer(a?a+"."+c:c)},"");for(var e=document.getElementById("containers");e.childNodes.length<c;)e.appendChild(b.ensureNode("container-"+(c-e.childNodes.length),e,function(b){return b.classList.add("container")}));b.renderDescription(d)}else console.warn("smalldoc.show: Cannot find symbol `"+a+"`")};b.onHashChange=function(a){b.show(window.location.hash.substr(1))};b.renderDescription=function(a){for(var c=document.getElementById("description");c.firstChild;)c.removeChild(c.firstChild);
if(a){a.id.split(".").pop();c.setAttribute("data-type",a.type);c.setAttribute("data-id",a.id);c.appendChild(html.div({_:"overview"},html.h1(b.renderName(a))));if(a.representation){var d=html.pre();d.innerHTML=a.representation;c.appendChild(html.div({_:"representation"},d))}d=html.div({_:"documentation docstring","data-type":a.type});d.innerHTML=a.documentation||"<div class='undocumented'>Undocumented</div>";c.appendChild(d);a.children&&(d=b._getGroups(a.children,b.GROUPS_CHILDREN).map(function(a){return b.renderGroup(a[1],
a[0],"children")}),c.appendChild(html.div({_:"children","data-type":a.type},d)));a=b.renderRelations(a);c.appendChild(a)}else console.warn("smalldoc.renderDescription: no element was given")};b.renderName=function(a,c,d,e){void 0===c&&(c=void 0);void 0===d&&(d=".");void 0===e&&(e=null);var f=b.STATE.symbols[a];"object"==typeof a&&(c=c||b._getGroup(a),a=a.id,f=!0);var g=(a||"__root__").split(d),h=1<g.length?g[g.length-2]:"__root__",k=g.pop();return html.div({_:"name","data-type":c,"data-name":a},html.span({_:"type"}),
html.span({_:"parents","data-count":""+h.length},g.reduce(function(a,c){a.prefix.push(c);var e=a.prefix.join(d);a.children.push((b.STATE.symbols[e]&&html.a||html.span)({_:"parent",href:"#"+e},c));return a},{prefix:[],children:[]}).children),(f&&html.a||html.span)({_:"symbol",href:"#"+a},k),e)};b.renderContainer=function(a,c,d){void 0===d&&(d=null);(a.id||a.name||"__root__").split(".");d=d||a.type||("__root__"==c?"root":"generic");return b._addContainer(html.div({_:"container","data-type":d,id:a.id||
a.name||"__root__"},html.div({_:"title"},b.renderName(c,d)),b._getGroups(a.children,b.OPTIONS.sort[d]).map(function(a){return b.renderGroup(a[1],a[0])})))};b.renderGroup=function(a,c,d){void 0===d&&(d=null);return html.div({_:"group"},html.div({_:"title","data-key":c.split(" ").join("-").toLowerCase()},c),b.renderSlots(a,d))};b.renderSlots=function(a,c){void 0===c&&(c=null);return html.ul({_:"slots"},a.map(function(a){b.STATE.symbols[a[1].id||a[0]]=a[1];a[1].children&&b.renderContainer(a[1],a[1].id||
a[0]);var d=b._getGroup(a[1]);return html.div({_:"slot"+(a[1].documentation?"":" undocumented"),"data-type":d,id:"slot:"+(a[1].id||a[0])},html.a({href:"#"+a[1].id||a[0]},b.renderName(a[0],d),b._renderSlot(a,c)))}))};b._renderSlot=function(a,c){void 0===c&&(c=null);var d=a[1];if("children"==c){var e=[],f=html.div({_:"docstring"});f.innerHTML=d.documentation||"<div>Undocumented</div>";e.push(html.div({_:"type"},b._getGroup(d)));e.push(f);return e}return null};b.renderRelations=function(a){var c=[],
d=(a.relations||[]).reduce(function(a,b){var d=b[0];-1==c.indexOf(d)&&c.push(d);void 0===a[d]&&(a[d]=[]);a[d].push(b);return a},{});return html.div({_:"relations"},c.sort().map(function(a){var c=d[a].reduce(function(a,c){var d=b.renderRelation(c);d&&a.push(html.li(d));return a},[]);return 0<c.length&&html.div({_:"relation","data-type":a},html.h2(a),html.ul(c))||null}))};b.renderRelation=function(a){var c=a[0];if("defined in"==c){var d=b.STATE.symbols[a[1]];return html.span({_:"defined"},d&&html.a({href:"#"+
d.id},b.renderName(d))||a[1])}return"next"==c||"previous"==c||"parent"==c?(d=b.STATE.symbols[a[1]],html.span({_:c},d&&html.a({href:"#"+d.id},b.renderName(d))||a[1])):"source"==c?(c=a[1],a=a[2],html.span({_:"source file"},html.a({href:c+"#"+a[0]+"-"+a[1],target:"source"},b.renderName(c,"file","/",html.span({_:"offset"},html.span({_:"start"},a[0]),html.span({_:"end"},a[1])))))):null};b._getGroup=function(a){if(a)return b.GROUPS.find(function(b){return-1<(a.tags||[]).indexOf(b)})||a.type||"value";console.warn("smalldoc._getGroup: Element is not defined:",
a);return null};b._getGroups=function(a,c){void 0===c&&(c=!0);var d=a.reduce(function(a,c){var d=b._getGroup(c[1]);void 0===a[d]&&(a[d]=[]);a[d].push(c);return a},{});return b.GROUPS.reduce(function(a,b){var e=d[b];"object"==typeof e&&(!0===c&&e.sort(function(a,b){return a[0].localeCompare(b[0])}),"function"===typeof c&&(e=c(e)),a.push([b,e]));return a},[])};b._addContainer=function(a,b){void 0===b&&(b="hidden");var c=document.getElementById(b);c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a);
return a};b._clearContainers=function(){for(var a=document.getElementById("containers"),c=document.getElementById("hidden");0<b.STATE.active.length;)b.STATE.active.pop().classList.remove("active");for(;a.firstChild;)c.appendChild(a.firstChild)};b._showContainer=function(a){var c=document.getElementById(a),d=document.getElementById("slot:"+a);d&&(b.STATE.active.push(d),d.classList.add("active"));c?document.getElementById("containers").appendChild(c):console.warn("smalldoc._showContainer: cannot find container `"+
a+"`");return a};b.init=function(){};"undefined"!=typeof b.init&&b.init();return b})(smalldoc);
