var $jscomp={scope:{},findInternal:function(b,a,c){b instanceof String&&(b=String(b));for(var d=b.length,e=0;e<d;e++){var f=b[e];if(a.call(c,f,e,b))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in c||(c[e]={});c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6-impl","es3");var smalldoc="undefined"!=typeof extend?extend.module("smalldoc"):"undefined"!=typeof smalldoc?smalldoc:{};
(function(b){b.FONTS="Fira+Mono|Fira+Sans";b.DATA=null;b.OPTIONS={containers:3,data:"api.json"};b.STATE={active:[],symbols:{}};b.GROUPS="parent;module;class;class constructor;class attribute;class method;attribute;method;function;value".split(";");b.loadCSS=function(a){void 0===a&&(a=b.FONTS);a=html.link({href:"https://fonts.googleapis.com/css?family="+a,rel:"stylesheet"});document.head.appendChild(a);return a};b.load=function(a){void 0===a&&(a=b.OPTIONS.data);fetch(a).then(function(a){return a.json().then(b.setup)})};
b.setup=function(a){void 0===a&&(a=b.DATA);b.DATA=a;var c=b.ensureNode("smalldoc",document.body);b.ensureNode("containers",c);b.ensureNode("description",c);b.ensureNode("hidden",c);b.ensureNode("about",c,function(b){b.innerHTML="<a href='https://github.com/sebastien/smalldoc'>smalldoc</a>"});b.render(a);window.addEventListener("hashchange",b.onHashChange);b.onHashChange()};b.ensureNode=function(b,c,d){void 0===d&&(d=void 0);var a=document.getElementById(b);a||(a=html.div({id:b}),d&&d(a),c.appendChild(a));
return a};b.render=function(a){b.renderContainer(a,"Smalldoc")};b.show=function(a,c){void 0===c&&(c=b.OPTIONS.containers);b._clearContainers();b._showContainer("__root__");(a||"").split(".").reduce(function(a,c){return b._showContainer(a?a+"."+c:c)},"");for(var d=document.getElementById("containers");d.childNodes.length<c;)d.appendChild(b.ensureNode("container-"+(c-d.childNodes.length),d,function(b){return b.classList.add("container")}));(d=b.STATE.symbols[a])?b.renderDescription(d):console.warn("smalldoc.show: Cannot find symbol `"+
a+"`")};b.onHashChange=function(a){b.show(window.location.hash.substr(1))};b.renderDescription=function(a){for(var c=document.getElementById("description");c.firstChild;)c.removeChild(c.firstChild);var d=a.id.split("."),e=d.pop();c.appendChild(html.div({_:"overview"},html.h1(html.span({_:"type"},b._getGroup(a)),html.span({_:"parents"},d.map(function(b){return html.span({_:"parent name"},b)})),html.span({_:"name"},a.name||e))));a.representation&&(d=html.div({_:"representation"}),d.innerHTML=a.representation,
c.appendChild(d));d=html.div({_:"documentation"});d.innerHTML=a.documentation||"<div class='undocumented'>Undocumented</div>";c.appendChild(d);a=b.renderRelations(a);console.log(a);c.appendChild(a)};b.renderName=function(b,c){void 0===c&&(c=void 0);var a=(b||"__root__").split("."),e=1<a.length?a[a.length-2]:"__root__",f=a.pop();return html.div({_:"name","data-type":c,"data-name":b},html.span({_:"type"}),html.span({_:"parents","data-count":""+e.length},a.map(function(b){return html.span({_:"parent"},
b)})),html.span({_:"symbol"},f))};b.renderContainer=function(a,c){var d=(a.id||a.name||"__root__").split("."),e=a.type||("__root__"==c?"root":"generic");return b._addContainer(html.div({_:"container","data-type":e,id:a.id||a.name||"__root__"},html.div({_:"title"},html.a({href:"#"+(1<d.length?d[d.length-2]:"__root__")},b.renderName(c,e))),b._getGroups(a.children).map(function(a){return b.renderGroup(a[1],a[0])})))};b.renderGroup=function(a,c){return html.div({_:"group"},html.div({_:"title","data-key":c.split(" ").join("-").toLowerCase()},
c),b.renderSlots(a))};b.renderSlots=function(a){return html.ul({_:"slots"},a.map(function(a){a[1].children&&b.renderContainer(a[1],a[1].id||a[0]);b.STATE.symbols[a[1].id||a[0]]=a[1];return html.div({_:"slot"+(a[1].documentation?"":" undocumented"),"data-type":a[1].type,id:"slot:"+(a[1].id||a[0])},html.a({href:"#"+a[1].id||a[0]},b.renderName(a[0],a[1].type)))}))};b.renderRelations=function(a){var c=[],d=(a.relations||[]).reduce(function(a,b){var d=b[0];-1==c.indexOf(d)&&c.push(d);void 0===a[d]&&(a[d]=
[]);a[d].push(b);return a},{});return html.div({_:"relations"},c.sort().map(function(a){return html.div({_:"relation","data-type":a},html.h2(a),html.ul(d[a].map(function(a){return html.li(b.renderRelation(a))})))}))};b.renderRelation=function(a){var c=a[0];if("defined"==c){var d=b.STATE.symbols[a[1]];return html.span({_:"defined"},html.span({_:"name","data-type":b._getGroup(d)},html.a({href:"#"+a[1]},a[1])))}return"defines"==c?(c=a[1],html.span({_:"defines"},html.span({_:"name","data-type":b._getGroup(d)},
c,"=",html.a({href:"#"+a[1]},a[1])))):null};b._getGroup=function(a){return b.GROUPS.find(function(b){return-1<(a.tags||[]).indexOf(b)})||a.type||"value"};b._getGroups=function(a,c){void 0===c&&(c=!0);var d=a.reduce(function(a,c){var d=b._getGroup(c[1]);void 0===a[d]&&(a[d]=[]);a[d].push(c);return a},{});return b.GROUPS.reduce(function(a,b){var e=d[b];"object"==typeof e&&(c&&e.sort(function(a,b){return a[0].localeCompare(b[0])}),a.push([b,e]));return a},[])};b._addContainer=function(a,b){void 0===
b&&(b="hidden");var c=document.getElementById(b);c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a);return a};b._clearContainers=function(){for(var a=document.getElementById("containers"),c=document.getElementById("hidden");0<b.STATE.active.length;)b.STATE.active.pop().classList.remove("active");for(;a.firstChild;)c.appendChild(a.firstChild)};b._showContainer=function(a){var c=document.getElementById(a),d=document.getElementById("slot:"+a);d&&(b.STATE.active.push(d),d.classList.add("active"));
c?document.getElementById("containers").appendChild(c):console.warn("smalldoc: cannot find container `"+a+"`");return a};b.init=function(){};"undefined"!=typeof b.init&&b.init();return b})(smalldoc);
